# Qdrant
#
# See https://qdrant.tech/documentation/

networks:
  default:
    name: ${LLEMONSTACK_NETWORK_NAME}
    external: true

volumes:
  qdrant_storage:

services:
  qdrant:
    image: qdrant/qdrant:v1.12.1@sha256:d774e7bb65744454984c6021637a0da89271f30df15e48601a9fafc926d26b1f
    container_name: qdrant
    labels:
      dev.dozzle.group: Vector Stores
    restart: unless-stopped
    # environment:
    # See https://qdrant.tech/documentation/guides/configuration/
    # - QDRANT__SERVICE__API_KEY=123
    # - QDRANT__LOG_LEVEL=debug
    ports:
      - 127.0.0.1:6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage
